export const news = [
  {
    title: "New News",
    text: "lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adit lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adit lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsumorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adit lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsumorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor ",
    image: "https://avatars.githubusercontent.com/u/140929886?v=4",
    likes: 2,
    comments: 5,
  },
  {
    title: "New News 2",
    text: "lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor ",
    image: "https://avatars.githubusercontent.com/u/140929886?v=4",
    likes: 2,
    comments: 5,
  },
  {
    title: "New News 3",
    text: "lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor ",
    image: "https://avatars.githubusercontent.com/u/140929886?v=4",
    likes: 2,
    comments: 5,
  },
  {
    title: "New News 4",
    text: "lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor ",
    image: "https://avatars.githubusercontent.com/u/140929886?v=4",
    likes: 2,
    comments: 5,
  },
  {
    title: "New News 5",
    text: "lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor ",
    image: "https://avatars.githubusercontent.com/u/140929886?v=4",
    likes: 2,
    comments: 5,
  },
  {
    title: "New News 6",
    text: "lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor ",
    image: "https://avatars.githubusercontent.com/u/140929886?v=4",
    likes: 2,
    comments: 5,
  },
  {
    title: "New News 7",
    text: "lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor lorem ipsum dolor sit amet, consectetur adip lorem ipsum dolor ",
    image: "https://avatars.githubusercontent.com/u/140929886?v=4",
    likes: 2,
    comments: 5,
  },
];
